# Generated by Django 4.1 on 2022-08-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BNB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Open", models.FloatField()),
                ("High", models.FloatField()),
                ("Low", models.FloatField()),
                ("Close", models.FloatField()),
                ("AdjClose", models.FloatField()),
                ("Volume", models.FloatField()),
            ],
            options={
                "ordering": ("Date",),
            },
        ),
        migrations.CreateModel(
            name="BTC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Open", models.FloatField()),
                ("High", models.FloatField()),
                ("Low", models.FloatField()),
                ("Close", models.FloatField()),
                ("AdjClose", models.FloatField()),
                ("Volume", models.FloatField()),
            ],
            options={
                "ordering": ("Date",),
            },
        ),
        migrations.CreateModel(
            name="ETH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Open", models.FloatField()),
                ("High", models.FloatField()),
                ("Low", models.FloatField()),
                ("Close", models.FloatField()),
                ("AdjClose", models.FloatField()),
                ("Volume", models.FloatField()),
            ],
            options={
                "ordering": ("Date",),
            },
        ),
    ]
